### ISSUE TITLE
部署失败

### ISSUE THREAD

**Issue by 100759** [wflixu/nblog#3]
您好，看到这个项目真的不错，但是总是部署失败，能否出个教程和notion模版

**Comment by wflixu** [comment]
1. 需要 notion  的2个参数
2. 查询的 对应条件，Notion database 也要有字段
![image](https://github.com/user-attachments/assets/ae056cd6-42c4-43b7-ab69-c40a47b9b9cf)

![image](https://github.com/user-attachments/assets/3bd23247-ac85-4743-aef2-04ed1702cf00)

**Comment by wflixu** [comment]
教程：http://blog.wflixu.cn/posts/a611469e-bac8-46cb-977a-082146a9a62e.html
